# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: step-test

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10

# you can overwrite defaults here
  stage: dev
  region: ap-northeast-1
  memorySize: 256
  timeOut: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource:
        - arn:aws:lambda:${self:provider.region}:${self:custom.config.accountId}:function:${self:service}-${self:custom.config.stage}-parallel

custom:
  config:
    accountId: "your Account ID"
    stage: ${opt:stage, self:provider.stage}

functions:
  first:
    handler: handler.first
  second:
    handler: handler.second
    environment:
      TARGET_LAMBDA_ARN: ${self:service}-${self:custom.config.stage}-parallel
  parallel:
    handler: handler.parallel
resources: ${file(./resources/state_machine.yml)}
